### ISSUE TITLE
Is there a help menu to use the commands?

### ISSUE THREAD

**Issue by EmanuelFaria** [webpilot-ai/ChatLongDoc#1]
Hello, I'm a non-coder runing on MacOS. I'd like to try your software, but I don't know how to get it to run.
Would you please add some more detail to the ReadMe?

I've tried:

`ChatLongDoc -h`
and
`ChatLongDoc --help`

I have installed it successfully, and cd to `ChatLongDoc` but I'm not sure how to input the arguments.
Below is some of my log. Would you please tell me what to do to make it work?
Thanks very much!

Manny

`EF@EFS-MacBook ~ % cd ChatLongDoc`
`EF@EFS-MacBook ChatLongDoc % python3 -m ChatLongDoc from utils import *`
`/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: No module named ChatLongDoc`
`EF@EFS-MacBook ChatLongDoc % python3 -m ChatLongDoc get_text /Users/emanuelfarruda/ChatLongDoc/example/example.pdf`
`/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: No module named ChatLongDoc`
`EF@EFS-MacBook ChatLongDoc % ChatLongDoc`

**Comment by ChiyuSONG** [comment]
Hi,

Apologies for the delay in responding. The project can now be executed using command lines. Kindly refer to the instructions in the README.

Additionally, may I suggest checking out our ChatGPT plugins at https://chat.openai.com/?model=gpt-4-plugins. ChatGPT PLUS is currently required to access similar features.

Thank you.
