### ISSUE TITLE
Useless documentation...

### ISSUE THREAD

**Issue by microfx** [webpilot-ai/ChatLongDoc#2]
Why are people always too lazy to give CLEAR instructions how to use their code? No word how to actually use URLs with this. Deleting this again. Timewaster.

**Comment by ChiyuSONG** [comment]
Hello there!

I understand your exhaustion and our project is meant to be helpful. To input the URL is just like passing any file path to the program. We have included an example in demo.ipynb and added support for running the program via command lines. 

I suggest checking out the updated instructions and our ChatGPT plugin at https://chat.openai.com/?model=gpt-4-plugins.
